// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4XaBVkgaeUlXYRitnA7voAqvLI6vvVu8',
    appId: '1:569244456339:web:ac96e0e53138c95c9b8466',
    messagingSenderId: '569244456339',
    projectId: 'e-commerce-4b119',
    authDomain: 'e-commerce-4b119.firebaseapp.com',
    storageBucket: 'e-commerce-4b119.firebasestorage.app',
    measurementId: 'G-3JVWB7WHFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA51dv9w6X3Ptex7KlRH15nV0Ypbe9rHGk',
    appId: '1:569244456339:android:afaa8dac57dbe1fb9b8466',
    messagingSenderId: '569244456339',
    projectId: 'e-commerce-4b119',
    storageBucket: 'e-commerce-4b119.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOmYwEdh_Dfk6sV4eFWEdOWjjMmtlBhH0',
    appId: '1:569244456339:ios:2818737248771b249b8466',
    messagingSenderId: '569244456339',
    projectId: 'e-commerce-4b119',
    storageBucket: 'e-commerce-4b119.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOmYwEdh_Dfk6sV4eFWEdOWjjMmtlBhH0',
    appId: '1:569244456339:ios:2818737248771b249b8466',
    messagingSenderId: '569244456339',
    projectId: 'e-commerce-4b119',
    storageBucket: 'e-commerce-4b119.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4XaBVkgaeUlXYRitnA7voAqvLI6vvVu8',
    appId: '1:569244456339:web:8ae095f9f47944b79b8466',
    messagingSenderId: '569244456339',
    projectId: 'e-commerce-4b119',
    authDomain: 'e-commerce-4b119.firebaseapp.com',
    storageBucket: 'e-commerce-4b119.firebasestorage.app',
    measurementId: 'G-G4ELF7PYEP',
  );
}
